export const regulations= [
    '§1. Postanowienia wstępne',
        '1. Regulamin serwisu internetowego ChessWebsiteWorld!, jest dokumentem określającym zasady dotyczące jego funkcjonowania oraz korzystania z jego zasobów przez Użytkownika.',
        '2. Każdy Użytkownik korzystający z serwisu automatycznie akceptuje niniejszy regulamin, zobowiązując się do jego przestrzegania',
        '3. Jeżeli Użytkownik nie zgadza się z przedstawionymi w nim warunkami zobowiązany jest do niezwłocznego opuszczenia serwisu.',
        '4. Serwis funkcjonuje pod adresem http://www.chesswebisteworld.pl/.',
        '5. Wszystkie gry oraz inne materiały, które znalazły się na łamach serwisu są całkowicie darmowe, korzystanie z nich nie wymaga uiszczania jakichkolwiek opłat dla ich autorów lub/i Administracji serwisu.',
        '6. Administracja serwisu nie ponosi odpowiedzialności za treści zawarte w grach i innych materiałach oraz za skutki korzystania z nich przez Użytkownika.',
    '§2. Warunki rejestracji i techniczne warunki korzystania z serwisu',
        '1. Rejestracja konta w serwisie jest darmowa, nie wymaga uiszczenia jakichkolwiek opłat na żadnym etapie korzystania z jego funkcjonalności.',
        '2. Przystępując do rejestracji Użytkownik wyraża zgodę na przesłanie drogą elektroniczną (na wskazany adres e-mail) wymaganych do ukończenia tego procesu powiadomień oraz informacji.',
        '3. Do prawidłowego funkcjonowania serwisu niezbędne jest:',
            'a.	Połączenie komputera z Internetem wynikające z posiadania odpowiedniego sprzętu.',
            'b.	Posiadanie dowolnej przeglądarki internetowej umożliwiającej wyświetlanie dokumentów hipertekstowych.',
            'c.	W przypadku rejestracji konta w serwisie niezbędne jest posiadanie konta poczty elektronicznej.',
            'd.	Oprogramowanie pozwalające na wyświetlanie elementów JavaScript.',
        '4. Użytkownik zobowiązuje się na własny koszt zapewnić sobie oprzyrządowanie niezbędne do korzystania z serwisu.',
    '§3. Użytkownicy',
        '1. Serwis ChessWebsiteWorld! oferuje Użytkownikowi możliwość dodawania komentarzy do rozegranych partyjek oraz prowadzenia dyskusji na ich temat, a także zgłaszania błędów oraz przedstawiania własnych propozycji za pomocą.',
        '2. Użytkownik może korzystać z serwisu jedynie w sposób zgodny z obowiązującym prawem.',
        '3. Podczas korzystania z serwisu zabronione jest:',
            'a.	używanie wobec innych Graczy określeń powszechnie uważanych za obraźliwe, a także wszystkich innych zachowań naruszających dobre obyczaje i godność osobistą drugiego człowieka;',
            'b.	używanie wulgaryzmów w jakimkolwiek języku;',
            'c.	zamieszczanie na łamach serwisu grafik i treści stanowiących relacje lub opisy aktów seksualnych oraz pornografii;',
            'd.	prześladowanie, dręczenie, zastraszanie oraz poniżanie ze względu na wyznawane poglądy, religię, rasę lub orientację seksualną;',
            'e.	propagowanie symboli i treści o tematyce faszystowskiej, komunistycznej lub innej totalitarnej; wszystkie kwestie z tym związane reguluje dodatkowo art. 256 Kodeksu karnego (Dz. U. z 1997 r. Nr 88, poz. 553);',
            'f.	propagowanie symboli i treści o tematyce rasistowskiej, a także wszelkich innych form dyskryminacji i nienawiści, wszystkie kwestie z tym związane reguluje dodatkowo art. 257 Kodeksu karnego (Dz. U. z 1997 r. Nr 88, poz. 553);',
            'g.	praktykowanie zachowań szkalujących, oszukańczych, naruszających prywatność, napastujących;',
            'h.	przesyłanie dowolnych materiałów łamiących prawa autorskie, tajemnice handlowe oraz prawa do wykorzystywania wizerunku;',
            'i.	podszywanie się pod inną osobę lub podmiot;',
            'j.	podawanie jakichkolwiek fałszywych informacji celem zaszkodzenia innej osobie;',
            'k.	podjudzanie przeciwko innemu Użytkownikowi lub/i Administracji serwisu oraz nawoływanie do popełnienia przestępstwa;',
            'l.	przesyłanie szkodliwego oprogramowania lub kodu, które mogą w jakikolwiek sposób zakłócić prawidłowe funkcjonowanie serwisu lub/i oprogramowania Użytkowników;',
            'm.	zakłócanie warunków korzystania z serwisu przez innych Użytkowników;',
            'n.	przesyłanie materiałów reklamowych bez uprzedniej zgody Administracji serwisu.',
        '4.	Administracja nie ponosi odpowiedzialności za wyrażane przez Użytkownika poglądy.',
        '5.	Administracja serwisu zastrzega sobie prawo do usunięcia komentarza lub/i wpisu w ChessWebsiteMaster który narusza postanowienia niniejszego regulaminu.',
        '6.	Administracja serwisu zastrzega sobie prawo do usunięcia nazwy Użytkownika wybranej w procesie rejestracji jeśli uzna, że łamie ona postanowienia niniejszego regulaminu.',
        '7.	Użytkownik zobowiązuje się do korzystania z serwisu w sposób bezpieczny; głównie dokładając starań, aby uzyskanie dostępu do konta było niemożliwe dla osób trzecich.',
        '8.	Konsekwencje wynikające z nieprzestrzegania regulaminu dla Użytkownika:',
            ' .	Użytkownik, który naruszy postanowienia regulaminu otrzymuje jedno słowne ostrzeżenie od Administracji serwisu.',
            'a.	Drugie naruszenie regulaminu skutkuje trwałą blokadą konta (tzw. banem).',
            'b.	Notoryczne łamanie regulaminu serwisu Kaboom! może skutkować blokadą nałożoną na adres IP Użytkownika przez Administrację.',
            'c.	Administracja zastrzega sobie prawo do niezwłocznego usunięcia z serwisu treści łamiących postanowienia niniejszego regulaminu bez uprzedniego informowania autora.',
        '9.	Użytkownik w swoim osobistym profilu ma możliwość ujawnienia na swój temat dobrowolnie dowolnych danych. Wszystkie te informacje są dostępne dla pozostałych Użytkowników, a Administracja nie ponosi odpowiedzialności za ujawnianie ich.',
    '§4. Ograniczenia wiekowe i Użytkownicy nieletni',
        '1.	Użytkownik samodzielnie zakładający konto w serwisie oświadcza, iż ukończył 13 rok życia.',
        '2.	Użytkownik, który nie ukończył 13 roku życia powinien korzystać z zasobów serwisu pod nadzorem osoby dorosłej (rodzica/opiekuna).',
        '3.	Niektóre materiały zamieszczone w serwisie mogą zawierać oznaczenie „18+” i są przeznaczone wyłącznie dla Użytkowników pełnoletnich.',
        '4.	Administracja nie ponosi odpowiedzialności za konsekwencje korzystania z serwisu osób poniżej 13 roku życia bez nadzoru osoby dorosłej oraz korzystanie z materiałów oznaczonych jako nieodpowiednie dla nieletnich.',
        '5.	Osoba umożliwiająca Użytkownikowi poniżej 13 roku życia korzystanie z serwisu zobowiązuje się do sprawowania nad nim opieki i ponosi wszelką odpowiedzialność za jego działania na łamach serwisu.',
        '6.	Osoba sprawująca opiekę nad Użytkownikiem poniżej 13 roku życia wyraża zgodę na wzięcie na siebie odpowiedzialności za wszelkie ewentualne szkody i konsekwencje, które mogą wyniknąć z korzystania z serwisu (także poprzez interakcje z innymi Użytkownikami).',
    '§5. Prawa autorskie i własności',
        '1.	Prawa autorskie określają ogół uprawnień przysługujących autorom materiałów (gier, grafiki, skryptu, tekstu etc.).',
        '2.	Wszystkie nazwy i znaki towarowe pojawiające się w materiałach zamieszczanych na łamach serwisu są własnością swoich autorów lub/i podmiotów na które zostały one przeniesione w całości lub w części.',
        '3.	Wszystkie materiały zamieszczone na łamach serwisu oraz tekst i grafika w nich zawarte objęte są prawami autorskimi oraz są własnością ich twórców lub/i producentów.',
        '4.	Szata graficzna, tekst oraz skrypt serwisu są objęte prawami autorskimi. W związku z tym kategorycznie zabronione jest kopiowanie oraz wykorzystywanie jakichkolwiek elementów bez uprzedniej zgody autorów.',
        '5.	Zabronione jest stosowanie praktyk takich jak ramkowanie części witryny serwisu, odtwarzanie, tłumaczenie na inne języki, kopiowanie, modyfikowanie, sprzedaż lub pożyczenie jakichkolwiek elementów serwisu bez uprzedniej pisemnej zgody Administracji.',
        '6.	Zabrania się hotlinkowania wszelkich materiałów zamieszczonych w ramach domeny serwisu bez wyraźnego i jednoznacznego podania źródła ich pochodzenia.',
        '7.	W przypadku wystąpienia w grach zamieszczonych w serwisie niedziałających elementów, odpowiedzialność za przywrócenie ich poprawnego działania ponosi twórca lub/i producent danej gry.',
        '8.	Administracja serwisu dokłada wszelkich starań, aby nie zostały złamane prawa autorskie.',
        '9.	Wszystkie kwestie związane z prawami autorskimi, które nie zostały omówione powyżej reguluje ustawa z dnia 4 lutego 1994r. „O prawie autorskim i prawach pokrewnych” wraz z późniejszymi zmianami (Dz. U. z 2006 r. Nr 90, poz. 631).',
        '10.	Użytkownik może korzystać z materiałów zamieszczonych w serwisie jedynie w celach niekomercyjnych.',
        '11.	W przypadku naruszenia prawa autorskiego/ prawa własności intelektualnej osoba zainteresowana zobowiązana jest do przesłania formularzem kontaktowym niezbędnych danych (pełne dane kontaktowe, opis działania stanowiącego naruszenie, dokument poświadczający posiadane prawa autorskie, miejsce publikacji oryginału danego dzieła podpis elektroniczny lub fizyczny).',
    '§6. Postanowienia końcowe',
        '1.	Wszelkie kwestie, które nie zostały poruszone w niniejszym regulaminie są regulowane na podstawie obowiązującego w Polsce prawa.',
        '2.	Administracja serwisu zastrzega sobie prawo do zmiany niniejszego regulaminu w dowolnym momencie, o czym poinformuje Użytkownika na tej stronie.',
        '3.	O wszelkich zmianach Użytkownik zostanie poinformowany na tej stronie.',
        '4.	Każdy Użytkownik automatycznie wyraża zgodę na akceptację zmian wprowadzonych do regulaminu.',
        '5.	Powyższy regulamin obowiązuje od dnia 1 czerwca 2018r.',       
]